export { default as Boton } from './Boton'
export { default as Input } from './Input'
export { default as PopUp } from './PopUp'
export { default as Tostada } from './Tostada'
export { default as CardLoading } from './CardLoading'
export { default as PopUpCarousel } from './PopUpCarousel'
export { default as CardProducto } from './CardProducto'
export { default as BotonSecundario } from './BotonSecundario'
